language: java
jdk: oraclejdk8
sudo: required
dist: trusty
branches:
  only:
  - master
  - Autowired_ViewContainer
  - master-spring-1.1
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf "$HOME/.m2/repository/com/vaadin/*spring*"
