language: java
jdk: oraclejdk8
sudo: required
dist: trusty
script: "mvn -B -V -e test && mvn -B -V -e verify -Dvaadin.testbench.developer.license=$TESTBENCH_LICENSE"
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf "$HOME/.m2/repository/com/vaadin/*spring*"
